export const bibleDataEN = {
  "bibleBookList": [
      "Gen",
      "Exod",
      "Lev",
      "Num",
      "Deut",
      "Josh",
      "Judg",
      "Ruth",
      "1Sam",
      "2Sam",
      "1Kgs",
      "2Kgs",
      "1Chr",
      "2Chr",
      "Ezra",
      "Neh",
      "Esth",
      "Job",
      "Ps",
      "Prov",
      "Eccl",
      "Song",
      "Isa",
      "Jer",
      "Lam",
      "Ezek",
      "Dan",
      "Hos",
      "Joel",
      "Amos",
      "Obad",
      "Jonah",
      "Mic",
      "Nah",
      "Hab",
      "Zeph",
      "Hag",
      "Zech",
      "Mal",
      "Matt",
      "Mark",
      "Luke",
      "John",
      "Acts",
      "Rom",
      "1Cor",
      "2Cor",
      "Gal",
      "Eph",
      "Phil",
      "Col",
      "1Thess",
      "2Thess",
      "1Tim",
      "2Tim",
      "Titus",
      "Phlm",
      "Heb",
      "Jas",
      "1Pet",
      "2Pet",
      "1John",
      "2John",
      "3John",
      "Jude",
      "Rev"
  ],
  "audioTreasureType": true,
  "curPath": "https://audiotreasure.com/content/WEBD_AT/",
  "title": "Audio Bible",
  uniqueID: "AudioTreasure.WEB_AT",
  "description": "Public domain",
  "language": "eng",
  "mediaType": "bible",
  "image": {
      "origin": "Local",
      "filename": "pics/Bible_OT.png"
  }
}

export const bibleDataDE_ML_1912 = {
    "bibleBookList": [
        "Gen",
        "Exod",
        "Lev",
        "Num",
        "Deut",
        "Josh",
        "Judg",
        "Ruth",
        "1Sam",
        "2Sam",
        "1Kgs",
        "2Kgs",
        "1Chr",
        "2Chr",
        "Ezra",
        "Neh",
        "Esth",
        "Job",
        "Ps",
        "Prov",
        "Eccl",
        "Song",
        "Isa",
        "Jer",
        "Lam",
        "Ezek",
        "Dan",
        "Hos",
        "Joel",
        "Amos",
        "Obad",
        "Jonah",
        "Mic",
        "Nah",
        "Hab",
        "Zeph",
        "Hag",
        "Zech",
        "Mal",
        "Matt",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Rom",
        "1Cor",
        "2Cor",
        "Gal",
        "Eph",
        "Phil",
        "Col",
        "1Thess",
        "2Thess",
        "1Tim",
        "2Tim",
        "Titus",
        "Phlm",
        "Heb",
        "Jas",
        "1Pet",
        "2Pet",
        "1John",
        "2John",
        "3John",
        "Jude",
        "Rev"
    ],
    "audioBible_de_ML": true,
    "curPath": "https://info2.sermon-online.com/german/MartinLuther-NT-1956-AT-1964/",
    "title": "Hörbibel",
    uniqueID: "SermonOnline.ML_1956",
    "description": "Public domain",
    "language": "deu",
    "mediaType": "bible",
    "image": {
        "origin": "Local",
        "filename": "pics/Bible_OT.png"
    }
  }

  export const bibleDataDE_TJ_HJ = {
    "bibleBookList": [
        "Gen",
        "Exod",
        "Lev",
        "Num",
        "Deut",
        "Josh",
        "Judg",
        "Ruth",
        "1Sam",
        "2Sam",
        "1Kgs",
        "2Kgs",
        "1Chr",
        "2Chr",
        "Ezra",
        "Neh",
        "Esth",
        "Job",
        "Ps",
        "Prov",
        "Eccl",
        "Song",
        "Isa",
        "Jer",
        "Lam",
        "Ezek",
        "Dan",
        "Hos",
        "Joel",
        "Amos",
        "Obad",
        "Jonah",
        "Mic",
        "Nah",
        "Hab",
        "Zeph",
        "Hag",
        "Zech",
        "Mal",
        "Matt",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Rom",
        "1Cor",
        "2Cor",
        "Gal",
        "Eph",
        "Phil",
        "Col",
        "1Thess",
        "2Thess",
        "1Tim",
        "2Tim",
        "Titus",
        "Phlm",
        "Heb",
        "Jas",
        "1Pet",
        "2Pet",
        "1John",
        "2John",
        "3John",
        "Jude",
        "Rev"
    ],
    "audioBible_de_TJ_HJ": true,
    "curPath": "https://audiotreasure.com/content/WEBD_AT/",
    "title": "Hörbibel",
    "description": "Public domain",
    "language": "deu",
    "mediaType": "bible",
    "image": {
        "origin": "Local",
        "filename": "pics/Bible_OT.png"
    }
  }
    

export const bibleDataNT = {
  "bibleBookList": [
      "Matt",
      "Mark",
      "Luke",
      "John",
      "Acts",
      "Rom",
      "1Cor",
      "2Cor",
      "Gal",
      "Eph",
      "Phil",
      "Col",
      "1Thess",
      "2Thess",
      "1Tim",
      "2Tim",
      "Titus",
      "Phlm",
      "Heb",
      "Jas",
      "1Pet",
      "2Pet",
      "1John",
      "2John",
      "3John",
      "Jude",
      "Rev"
  ],
  "freeType": false,
  "pathPattern": [
      1,
      "_",
      3,
      "_",
      2,
      "_ENGWEBN2DA.mp3"
  ],
  "curPath": "shared/audio/English/English_NT",
  "title": "Audiobible NT",
  "image": {
      "origin": "Local",
      "filename": "img/ser07.jpg"
  },
  "language": "eng",
  "mediaType": "bible"
}
